### ISSUE TITLE
clean, stage and dist no more working after upgrade to 1.3 (invalid character).

### ISSUE THREAD

**Issue by almothafar** [mmizutani/sbt-play-gulp#26]
I'm getting invalid character at char 1 line 1 when I try to clean or stage play project, 

```
Will run: [cmd, /c, D:\Sources\PlayProject\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, build, --force] in D:\Sources\PlayProject\ui
java.io.IOException: [cmd, /c, D:\Sources\PlayProject\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, build, --force] in D:\Sources\PlayProject\ui failed with exit code 1
        at com.github.mmizutani.sbt.gulp.PlayGulpPlugin$.com$github$mmizutani$sbt$gulp$PlayGulpPlugin$$runGulp(PlayGulpPlugin.scala:178)
        at com.github.mmizutani.sbt.gulp.PlayGulpPlugin$$anonfun$playGulpSettings$9.apply(PlayGulpPlugin.scala:93)
        at com.github.mmizutani.sbt.gulp.PlayGulpPlugin$$anonfun$playGulpSettings$9.apply(PlayGulpPlugin.scala:89)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:gulpDist) java.io.IOException: [cmd, /c, D:\Sources\PlayProject\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, build, --force] in D:\Sources\PlayProject\ui failed with exit code 1
[error] Total time: 10 s, completed Dec 20, 2016 11:49:11 PM
```

**Comment by mmizutani** [comment]
Have you installed the Gulp package either globally or locally in the first place?

**Comment by almothafar** [comment]
@mmizutani it was installed already, and reinstall things was not helpful.
I downgraded this plugin to 0.1.1 and it worked again.

**Comment by mmizutani** [comment]
I am investigating why this line
```
https://github.com/mmizutani/sbt-play-gulp/blob/master/src/main/scala/com/github/mmizutani/sbt/gulp/PlayGulpPlugin.scala#L176
```
returns false on Windows but not on Linux.

**Comment by mmizutani** [comment]
I suppose this issue is the same as reported at http://stackoverflow.com/a/21534630/1478110.
So in version 0.1.4 I prepended "node " to the gulp command on Windows.

**Comment by almothafar** [comment]
@mmizutani not sure what you changed and what I have to do, but still, I have the same issue in 1.4 version as well.

>gulp -v
[11:18:57] CLI version 3.9.1

>node -v
v7.2.0

**Comment by mmizutani** [comment]
Remove the directories `target` and `%USERPROFILE%\.ivy2\local\com.github.mmizutani` and try with v0.1.4 again, please.
When calling the gulp command from inside the sbt console, you will see this log

<pre>
Will run: [cmd, /c, <b>node,</b> C:\Users\user\...\play-gulp-react\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, watch, --force] in C:\Users\user\...\play-gulp-react\ui
</pre>

instead of

<pre>
Will run: [cmd, /c, C:\Users\user\...\play-gulp-react\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, watch, --force] in C:\Users\user\...\play-gulp-react\ui
</pre>

On Windows with newer Gulp, this fails to run the locally-installed gulp executable:
```
> .\node_modules\gulp\bin\gulp.js
```

whereas this works fine:

```
> node .\node_modules\gulp\bin\gulp.js
```

**Comment by almothafar** [comment]
Strange, the `node` didn't prepended, the command was something like this:

`Will run: [cmd, /c, D:\Sources\PlayProject\ui\node_modules\gulp\bin\gulp.js, --gulpfile=gulpfile.js, clean, --force] in D:\Sources\PlayProject\ui`

I cleared the `.ivy2` cache, and got only 1.4 in the new cache and still have the same issue.

**Comment by mmizutani** [comment]
I have republished the version with "node" as version 0.1.5.

**Comment by almothafar** [comment]
Yay! Finally worked 👍

**Comment by mmizutani** [comment]
IMHO it is not quite advisable to run Ruby and Node.js on the Windows platform as there is a multitude of OS-specific subtleties related to native extensions and path handling like this. Tough roads ahead.
